# Generated by Django 5.0.2 on 2024-02-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
